### PR TITLE
set field nullable

### PR DESCRIPTION
**Pull request by numerogeek**
ping @mremi

### CODE REVIEW

**Comment by mremi** [comment]
Can you also update the `CHANGELOG.md` please?

**Comment by numerogeek** [comment]
Boom.

**Comment by mremi** [comment]
You need to rebase, I cannot merge it. I updated the `CHANGELOG.md` yesterday to re-order it by date desc.

**Comment by numerogeek** [comment]
ping @mremi

**Comment by mremi** [comment]
@numerogeek Wrong conflict resolving, the diff contains my last BC break and your change should be at the top of file

**Comment by numerogeek** [comment]
@mremi how can I fix that ?

**Comment by mremi** [comment]
Sorry, maybe I expressed myself poorly. You just have to edit the `CHANGELOG.md` like this:
```
CHANGELOG
=========

### master (2015-09-25)

* The fields are now optionals for doctrine. So you can remove some fields if you don't want them and store in database.

### master (2015-09-15)

* [BC BREAK] Removed ``mremi/bootstrap-bundle`` dependency.

### master (2015-01-28)

* Allow multiple To for Swift mailer
* [BC BREAK] Removed ``mremi_contact.email.recipient_adress`` config, replaced by ``mremi_contact.email.to``.

### master (2015-01-05)

* Allow any captcha form field type.
* [BC BREAK] Removed Genemu dependency.
* [BC BREAK] Removed ``mremi_contact.form.captcha_disabled`` configuration option.
```

**Comment by numerogeek** [comment]
ping ? :)

**Comment by mremi** [comment]
Almost done..can you remove the duplicated lines at the top of `CHANGELOG.md` please? :)
See the diff https://github.com/mremi/ContactBundle/pull/30/files

**Comment by numerogeek** [comment]
ping :)

**Comment by mremi** [comment]
Thanks @numerogeek !

**Comment by numerogeek** [comment]
No prob ! 
By the way, I have included your bundle in a project I started a couple of weeks. Basically it's an install of symfony with some enabled and configured bundles required in almost all projects.
It also comes with an admin part. (it's not an abstraction layer, just a theme) 

Do not hesitate to have a look and give me any feedbacks :)

https://github.com/numerogeek/ultimate-symfony2-boilerplate

**Pull request merged**
