### PR TITLE
Add spanish translations

### PR DESCRIPTION
**Pull request by fcpauldiaz**
Fixes issue #32  regarding to empty email content

### CODE REVIEW

**Comment by mremi** [comment]
Hi @fcpauldiaz Thank you for this PR, can you squash your commits to have only one please?

**Comment by fcpauldiaz** [comment]
How do I squash the commits ?

**Comment by mremi** [comment]
Nop you can use this PR. To squash the commits, you need to use the interactive rebase like this:
```bash
$ git rebase -i HEAD~2
```
and then mark the first commit (second in the list) as `squash`

**Comment by fcpauldiaz** [comment]
Hey I had a merge with your most recent commit, I will make another PR.

**Comment by mremi** [comment]
Yep too many commits here :) Thanks

**Pull request closed without merging**
